on: [push]

name: Ant

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@master

    - name: Set up JDK 1.8
      uses: actions/setup-java@master
      with:
        version: 1.8

    - name: Build with Ant
      working-directory: ''
      run: ant -noinput -buildfile build.xml
