on: [push]

name: Dart

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@master

    - name: Install dependencies
      run: pub get

    - name: Run tests
      run: pub run test
