name: Elixir CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup elixir
      uses: actions/setup-elixir@v1.0.0
      with:
        elixir-version: 1.9.x # Define the elixir version [required]
        otp-version: 22.x # Define the OTP version [required]
    - name: Install Dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
    - name: Run Tests
      run: mix test
