name: Elixir CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache mix dependencies
      uses: actions/cache@v1
      with:
        path: deps
        key: ${{ runner.OS }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
          ${{ runner.OS }}-mix-
    - name: Cache build files
      uses: actions/cache@v1
      with:
        path: _build
        key: ${{ runner.OS }}-build-${{ github.sha }}
        restore-keys: |
          ${{ runner.OS }}-build-
    - name: Install dependencies
      run: mix deps.get
    - name: Run tests
      run: mix test