name: Nix

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.1
    - name: Install Nix
      uses: cachix/install-nix-action@v10
    - name: Install Cachix
    - uses: cachix/cachix-action@v6
      with:
        # Once you generate a binary cache on https://app.cachix.org, you'll need to insert the name of the cache here
        name: mycache
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - name: Run nix-build
      run: nix-build
    - name: Check nix-shell works
      run: nix-shell --run "echo OK"