name: Webpack CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: {{{ matrix.node-version }}}

    - name: npm install, build
      run: |
        npm install -g webpack webpack-cli --save-dev
        npm install
        npx webpack
