name: Aparna Validate This
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v2
    - name: Run validator
      uses: aparna-ravindra/workflow-template-validator@v0.4
      with:
        path-to-workflow-yaml: './ci,./automation'
        path-to-properties-json: './ci/properties,./automation/properties'
        path-to-icons: './icons'
